name : Deploy to staging 
on :
push:
branchs: [main]

jobs :
redeploy_everything:
runs-on : ubuntu-latest
name: Deploying everything  to staging cluster
steps :
-run : |
       echo "${{secrets.SSH_PRIVATE_KEY}}" &> ~ssh_key
       echo "yes" ssh -i ~/ssh_key root@(ip address)
       cd ci-cd/ && git pull
       pnpm install
       pnpm run build
       pm2 restart server